### Reads all the players
GET http://localhost:3000/api/players



### Creates a player object
POST http://localhost:3000/api/players
Content-Type: application/json

{
    "id": "5",
    "alias": "samzih",
    "team": "Looking For Org",
    "nationality": "Swedish"
}



### Updates the property value of a specific player based on id
PUT http://localhost:3000/api/players/5
Content-Type: application/json

{
    "team": "Astralis"
}



### Delete a specific player object based on id
DELETE http://localhost:3000/api/players/5